### ISSUE TITLE
Unable to check if Get() returns nothing

### ISSUE THREAD

**Issue by jfbus** [dancannon/gorethink#11]
As with rethinkgo, Get() always returns a single row and does not provide any way of checking if a record exists.

```
row := r.Table(table).Get("missing key").RunRow(rs)
err := row.Scan(obj)
// err == nil, obj has default values

rows, err := r.Table(table).Get("missing key").Run(rs)
// err == nil
for rows.Next() { // returns true
    err := rows.Scan(obj)
    // err == nil, obj has default values
}
```

GetAll works :

```
rows, err := r.Table(table).GetAll("missing key").Run(rs)
// err == nil
for rows.Next() { // returns false
    err := rows.Scan(obj)
}
```

RethinkDB returns a single NULL datum on Get queries returning no result, and this null value is scanned to the object.

Proposition :
- [BC break] ResultRow.Scan returns ErrNotFound on NULL datum (as works mgo for MongoDB in similar cases)
- add func (*ResultRow) IsNull() (or IsEmpty()/IsNil())

The code would work as follows :

```
row := r.Table(table).Get("missing key").RunRow(rs)
err := row.Scan(obj)
// err == ErrNotFound

rows, err := r.Table(table).Get("missing key").Run(rs)
// err == nil
for rows.Next() && !rows.IsNull() { // true + false
    err := rows.Scan(obj)
}
```

If this is ok, I can prepare a PR.

[EDIT: replaced RunRow by Run on last piece of code]

**Comment by dancannon** [comment]
Hi, Thanks for the bug reports.

I agree that this is a problem and something I had forgotten to sort out. I am not too worry about backwards compatibility until both RethinkDB and this driver are stable and I don't believe your changes will effect too many people either.

I think it would be good to have an IsNil method instead of having ErrNotFound. It might make sense to use IsEmpty for ResultRows and IsNil for ResultRow. Looking at the mgo API docs they use an error as they dont return a result struct.

If you could prepare a PR that would be great. I will look into sorting your other issues.

**Comment by jfbus** [comment]
Two possibilities :

```
func (r *ResultRow) IsNil() (bool, error)
```

or

```
func (r *ResultRow) IsNil() bool
```

The former allows to handle errors (`r.err != nil` and `r.rows.Next() == false`). The latter is simpler...

What do you prefer ?

**Comment by dancannon** [comment]
I personally prefer `func (r *ResultRow) IsNil() bool`, as you mentioned it is simpler and both ResultRow and ResultRows already have an Err function.

What do you prefer?

**Comment by jfbus** [comment]
Same as you...

**Comment by robert-zaremba** [comment]
In your example, why `rows.Next` should return `true` for a _missing key_?
We can just return `false`, and all things should work.

```
rows, err := r.Table(table).Get("missing key").RunRow(rs)
// err == nil
rows.Next() 
```

**Comment by jfbus** [comment]
I'm not sure, but there might be cases when a Run query returns a list of NULL values. Testing a NULL datum in Next() might cause problems in such queries.

I don't think the Get/Run/Next/Scan pattern will be often used compared to Get/RunRow/Scan.

Personally, having an awkward Get/Run/Next/Scan does not bother me.

**Comment by dancannon** [comment]
I dont think we should change the behavior of Next but adding the IsNil and
IsEmpty methods should work for all cases.

Having a NULL return value should be handled differently depending on the
query and this is up to the program which uses the driver.

**Comment by robert-zaremba** [comment]
What is a reason of `rows.Next()` being `true` where there is no value?

**Comment by jfbus** [comment]
RethinkDB always returns a row with a nil (NULL) value to Get queries for missing keys.

RethinkDB was created for dynamic/loosely typed langages in mind where nil (as in "not set") exists. Go has no notion of "not set", and this  adds complexity and/or awkwardness and/or whatever you name it in some use cases.

To be able to make Next() return false would require to test for this nil value, with side effects (on queries which would return an array of nil vaules) or to add complex code (if it can be done)

IMHO, that is not worth it

**Comment by dancannon** [comment]
Thanks for sorting this @jfbus.

**Comment by robert-zaremba** [comment]
Current API for `IsNil + Scan` pattern doesn't work with errors. 
I suggest to change the example (or API) because it misleads how to use it properly, eg for something like:

```
row := r.Table(table).Get("missing key").RunRow(rs)
// if a connection is broken then row.err != nil and row.IsNil() == true
err := row.Scan(&obj)
// check if obj exists:
err != nil && !row.IsNil()
}
```

Also it might lead to other bugs -> https://github.com/dancannon/gorethink/pull/16#commitcomment-4315877

**Comment by jfbus** [comment]
It might be better to have RunRow return `(*ResultRow, error)` and move `r.rows.Next()` + `r.rows.Close()` to RunRow.

All server related errors would occur in RunRow, and none in IsNil.

**Comment by dancannon** [comment]
I agree with @jfbus as this would also mean that we dont have to have the fetched field in ResultRow as it will always be fetched.

**Comment by jfbus** [comment]
PR follows.

Maaaaaany tests use `query.RunRow(sess).Scan(&response)` => PR is quite large

**Comment by robert-zaremba** [comment]
Yes, the API change is more clear :+1:

**Comment by robert-zaremba** [comment]
I know you want to hate me here ... 
While writing a code with current API version and `RunRow` pattern I found that I always call `IsNull` or `Scan`. I didn't found any interesting use-case when you want to handle error in different place then value.
So the pattern is always:

``` Go
row, _ := term.RunRow(s) // here we can skip error checking because it is the same as 2 lines below
var response someType
err :=row.Scan(&row)
```

or

``` Go
row, err := term.RunRow(s)
exists := row.IsNull()
```

From this observation the following `IsNull` declaration would be more consistent:

``` Go
func (*ResultRow) IsNil() (bool, error)
```

And everywhere we can simply write in one row:

``` Go
exists, err = term.RunRow(s).IsNull()
// or:
err = term.RunRow(s).Scan(&response)
```

If  @jfbus agrees I can PR (but for this we need to revert #22 )

**Comment by jfbus** [comment]
> I know you want to hate me here ... 

Daniel may be thinking we are two pains in the ass :smile: 

I find it strange to have Run return `(*ResultRows, error)` and RunRow just return `*ResultRow`. IsNil being just a test, I don't think it needs to return an error.

If you want compact code, you could also have :

``` go
err := term.RunAndScan(s, &response)
if _, ok := err.(*r.ErrorNilResult); ok {
  // not found
}
```

`RunAndScan` = `RunRow` + `IsNil` + `Scan`

and

``` go
exists := term.Exists(s)
```

`Exists` = `RunRow` + `IsNil`

... or you can have RunRow return a `ErrorNilResult` error when the returned row is nil.

**Comment by robert-zaremba** [comment]
The case it to find a nicely working API, and without using it we won't find it ;)

Providing `Exists` and `RunAndScan` makes `IsNil` and `Scan` useless (publicly).
Other option for `RunAndScan`: (*)

```
notNil, err := term.RunAndScan(s, &response)
```

I was also asking myself: _why we just can't set nil values for response as in rethinkdb first class drivers?_, but it looks that we need to support simple types which can't have nil values.
1. What about dropping err from `ResultRow.Scan()` (and in internall implementation of Scan and IsNil)?  
   If `RunRow` doesn't return non nil `error` then  `Scan` and `IsNil` shouldn't.
2. As in (*) we can get rid of `IsNil` by returning two values in `Scan`:
   
   ```
   // ok is true if value exists, err is nil when there are no internal DB / connection / serialization errors.
   func (r *ResultRows) Scan(dest interface{}) (ok bool, err error)
   func (r *ResultRow) Scan(dest interface{}) (ok bool, err error)
   ```

Personally I like the second option.

**Comment by jfbus** [comment]
You cannot remove err from `ResultRow.Scan()` because of unmarshalling errors

**Comment by robert-zaremba** [comment]
So 1. is out. What about 2. ?

**Comment by jfbus** [comment]
No particular opinion on the subject...

**Comment by dancannon** [comment]
Ok so firstly I agree with @jfbus as I think `IsNil` should only return a `bool`. My reasoning for this is that if the function returned multiple values then it becomes more difficult to use. 

I also think that the having the `IsNil` method for checking if no result was returned is the best as you might not always be scanning the result into a variable for example if you were just checking for the existence of some value (This also makes me think we might need some function for counting the number of elements found).

That being said I dont think any changes need to be made since looking at your code example @robert-zaremba in this [comment](https://github.com/dancannon/gorethink/issues/11#issuecomment-26332531) I think you are making the assumption that the error returned by RunRow and Scan are always the same however as mentioned by @jfbus `Scan` can return its own errors caused by unmarshalling.

Also while I dont mind breaking BC too much I am going to start saving any changes that do so until the RethinkDB releases.

**Comment by robert-zaremba** [comment]
In current implementation, `Scan` won't continue if there is already an error (ie the one caused by `RunRow`) - and will return that error. For checking existence one should use `Count` or `IsEmpty`.

Also is there any possibility where there will be a nil record for `Scan` on non _singleRowSelection_?
