### ISSUE TITLE
Add type aliases for map[string]interface{} and []interface{}

### ISSUE THREAD

**Issue by jfbus** [dancannon/gorethink#23]
I find `map[string]interface{}` and `[]interface{}` pretty awkward and verbose.

Why not define some aliases (as mgo does with bson.M) ?

```
type M map[string]interface{}
type S []interface{}
```

```
Expr(map[string]interface{}{"a": 1, "c": 3}).Merge(map[string]interface{}{"b": 2})
Do([]interface{}{map[string]interface{}{"a": 1}, map[string]interface{}{"a": 2}, map[string]interface{}{"a": 3}})
```

would become

```
Expr(r.M{"a": 1, "c": 3}).Merge(r.M{"b": 2})
Do(r.S{r.M{"a": 1}, r.M{"a": 2}, r.M{"a": 3}})
```

**Comment by dancannon** [comment]
I understand your reasoning behind this issue (And while developing the driver I included an Array and Obj type) however I think this is an issue more with Go types than GoRethinks implementation. However if you really want shortened types then I think it is best to do this in your own code since the driver will handle these types just fine as long as they map to `map[string]interface{}`/`[]interface{}` .

**Comment by jfbus** [comment]
Having aliases within the driver would greatly help writing easy to understand documentation and writing normalized code.

Go itself often uses such convenience types (`time.Duration`, `type Value interface{}` in sql/driver, `type Number string`or `type RawMessage []byte` in encoding/json, ...)

**Comment by dancannon** [comment]
Im still learning towards not adding convenience types for Map and Slice as I believe that it is not up to the driver to define data structures. Regarding writing normalized code I personally I think adding these types will has the opposite effect.

Unless anybody else has any other reasons I will close this issue.
