### ISSUE TITLE
Suggest to support json tags for scanning

### ISSUE THREAD

**Issue by linuxerwang** [dancannon/gorethink#63]
type Person struct {
   Id string    `gorethink:"id,omitempty"`
   Name string  `gorethink:"name"`
   Place string `gorethink:"place"`
}

goprotobuf generates go struct for json but not gorethink. It would be better for gorethink to identify json tags when scan the struct. For example, this is generated from the proto:

type Person struct {
   Id string    `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
   Name string  `protobuf:"bytes,2,name=name" json:"name"`
   Place string `protobuf:"bytes,3,name=place" json:"place"`
}

**Comment by dancannon** [comment]
Although GoRethink uses a similar method to encode and decode values there are some differences. Because of this I made the decision to not use `json` tags as it means that if either method changes there should not be any issues.

The old RethinkGo driver used to use json to encode structs and this caused a number of problems with the recent inclusion of pseudo-types(time).
