### ISSUE TITLE
Error:  gorethink: Token 3118 not in stream cache

### ISSUE THREAD

**Issue by timshannon** [dancannon/gorethink#77]
I'm getting this error inconsistently during Test runs specifically with the Limit RQL Term.  

It happens in maybe 1 in 10 _go test_ runs.

```
data_test.go:30: Error:  gorethink: Token 3118 not in stream cache. in:
        r.Db("test").Table("testing").Filter(func(var_5 r.RqlTerm) r.RqlTerm { return r.Row.Field("Group").Eq("group1") }).Limit(5)
```

I tried to duplicate the issue in a standalone test (https://gist.github.com/timshannon/11301394) but have yet to get it throw the error.

If I can get a standalone test scenario to fail like this, I'll add it to the issue, but for now I figured I'd open the issue to see if you have any clues.

Thanks,

**Comment by dancannon** [comment]
Ok without a reproducible error I cannot be sure however this seems to be an issue with the `Connection.SendQuery` function. I also don't think that the issue is specific to the Limit term unless there is an issue with the database.

I will have a look over the code and I can see if I can find the bug. Could you let me know if you are running multiple queries concurrently when you get this error?

Thanks,
Daniel

**Comment by timshannon** [comment]
Not concurrent. But several queries being run in the same session.

**Comment by dancannon** [comment]
Ok I think I might have fixed this bug. The issue was that there was a race condition because I was incrementing a global counter using `nextVarId++` not `atomic.AddInt64(&nextVarId, 1)`. Here is the change f57b2bc

If you could try the branch `hotfix/issue_77` and let me know if the problem has gone that would be great since I could not manage to replicate this issue exactly.

**Comment by timshannon** [comment]
Nope, still getting the error.  I'm still trying to build a replicatible standalone test.

**Comment by dancannon** [comment]
Ok second idea, if a previous query in the session had a large number of rows which causes RethinkDB to split the result then future queries seem not to work properly. I still cannot replicate this error message though.

**Comment by dancannon** [comment]
Ok good news I have managed to replicate the error however it is getting late here so I will have a look at it tomorrow.

**Comment by dancannon** [comment]
Could you try that branch again?

**Comment by timshannon** [comment]
Running great now.

Thanks

**Comment by dancannon** [comment]
Ok thanks, I still have some changes to make before I can merge this branch and I am busy for the next couple of days but this should be fine to use until then.

**Comment by ygabo** [comment]
What was the problem? Was it about the streaming change? Do you mind sharing how you fixed it? Thanks.

**Comment by timshannon** [comment]
See for yourself: https://github.com/dancannon/gorethink/compare/hotfix;issue_77

**Comment by dancannon** [comment]
There are quite a few changes and not all of them are directly related to this issue. The main reason that the "Token not in stream" error appeared is that the code that dealt with batched responses was completely broken. I don't know why I hadn't wrote tests for this and in my own usage of the driver I tend to use queries that return only around 100 rows at a time.

The issue with the batched responses was that I was not properly checking if the database had more rows to be fetched. Because the official drivers have recently had their resulting handling code improved to allow asynchronous fetching of future results I decided to rewrite the code from scratch.

I hope this helps @ygabo.
