### ISSUE TITLE
Not a bug,but a question

### ISSUE THREAD

**Issue by AlexLuya** [dancannon/gorethink#79]
I have a table that holds doc with structure like this:

{
  CreatorId:""
  CreateItme:345345\seconds from 1970....
}

And I want to use blow statement to query out all docs created by "user/001" within latest 8 days:

res, err := rt.Table(s.table).Filter(func(row rt.RqlTerm) rt.RqlTerm {
    return row.Field("CreatorId").Eq("user/001").And
                    (rt.Expr(time.Now().Unix()).Sub(row.Field("CreateTime")).
                    Le(86400 \* int32(8)))
}).Run(s.session)

and I know some docs do satisfy my expectation,but this query return nil,so

Would do you please tell where the mistakes is in my query statement?

**Comment by dancannon** [comment]
Hi,

So I think the issue you are having is that row.Field("CreateTime") is returning a time object but time.Now().Unix() is returning a timestamp. That being said I think using the `During` term would be better for what you are trying to do. For example:

``` go
rows, err := r.Db("test").Table("issue_79").Filter(func(row r.RqlTerm) r.RqlTerm {
    return row.Field("CreatorId").Eq("1").And(row.Field("CreateTime").During(
        r.Now().Sub(86400*8),
        r.Now(),
        r.DuringOpts{
            RightBound: "closed",
        },
    ))
}).Run(session)
if err != nil {
    log.Fatalln(err.Error())
}
```

I included the RightBound option so that if an item was created at the same time that the query was executed it would be included (I know this is unlikely to happen but I thought it would be worth pointing out).

Hope this helps,
Daniel
