### ISSUE TITLE
Bug: RunWrite() does not return error

### ISSUE THREAD

**Issue by sym3tri** [dancannon/gorethink#84]
If I execute a query with `RunWrite()` and it fails I would've expected the returned error value to be non-nil. Instead what I am seeing is a nil error value with result.Errors containing a non-zero value.

```
result, err := gorethink.Table(table).Insert(
    payload,
    gorethink.InsertOpts{Upsert: false},
).RunWrite(db)
```

**Comment by dancannon** [comment]
Hi,

Could you give me some more information about what you are doing to get this response as I have created the following tests and they seem to return the expected values. Also are you on the latest version of GoRethink (v0.2.1) as I have made some changes to the result code since v0.2.

``` go
func (s *RethinkSuite) TestQueryRunWriteError(c *test.C) {
    _, err := Db("test").Table("nonexistant").Insert(map[string]interface{}{
        "a": 1,
    }, InsertOpts{Upsert: false}).RunWrite(sess)
    c.Assert(err, test.NotNil)
}

func (s *RethinkSuite) TestQueryRunWriteIncorrectResponse(c *test.C) {
    _, err := DbList().RunWrite(sess)
    c.Assert(err, test.NotNil)
}
```

**Comment by sym3tri** [comment]
Hi, I was originally using 0.2 but I just confirmed the same issue on 0.2.1.

I am attempting to insert a document into a table that _does_ exist. The document I'm inserting has the same id as a document which already exists in the table.

**Comment by dancannon** [comment]
Ok thanks, I managed to replicate this when I inserted a document with a duplicate ID. It would seem that when this happens RethinkDB does not actually return an error in the way it usually does. I assume this is because a query can contain multiple writes so if one write fails that does mean that the entire query has failed so the `first_write` field is returned instead.

I see two options here, the first is to leave RunWrite how it is, the other option is to check the FirstError field and return an error if the field is not empty. I am not too keen to go for the last option because I usually assume that if the returned error is not nil then the query has failed and as mentioned this is not always the case with FirstError.

Has anybody else got any input here?

**Comment by timshannon** [comment]
My opinion is to not muddle the FirstError field.  I'm making the same assumptions you are in my code.

I see an error response from RunWrite as an error communicating or running the write.

Here's what my code looks like for checking for dupes:

```
     response, err := r.Db(db).Table(table).Insert(data).RunWrite(session)
     if err != nil {
             return err
     }
     if response.Errors > 0 {
             if strings.HasPrefix(response.FirstError, "Duplicate primary key") {
                     return ErrDupeKey
             }
             return errors.New(response.FirstError)
     }
     return nil
```

**Comment by sym3tri** [comment]
I wasn't really considering the multi-write case, so I guess the current implementation makes sense as long as it's consistent with the rest of the API.

Might be useful to document this though since the behavior is not completely obvious.

**Comment by dancannon** [comment]
I agree that it needs to be documented better. I also think its worth pointing out that this is not a really a GoRethink API choice but a RethinkDB one.

That being said I think this issue can be closed now. Thanks for the input.

**Comment by sym3tri** [comment]
Agreed. Thanks for looking into it.
