### ISSUE TITLE
ReQL composing error:cannot take the address of gorethink.Row.Field

### ISSUE THREAD

**Issue by AlexLuya** [dancannon/gorethink#88]
Based on sql composing experience,I tried to compose ReQL like this:

```
  func ForTime(startTime, endTime int64) *rt.RqlTerm {
    if startTime != -1 {
        return &(rt.Row.Field(START_TIME).Gt(startTime).And(rt.Row.Field(END_TIME).Lt(endTime)) )
    }

    return nil
}
```

but I got a compilation error:

```
cannot take the address of gorethink.Row.Field(START_TIME).Gt(startTime).And(gorethink.Row.Field(END_TIME).Lt(endTime))
```

**Comment by dancannon** [comment]
I think if you remove the pointer the error should go away.

``` go
  func ForTime(startTime, endTime int64) rt.RqlTerm {
    if startTime != -1 {
        return rt.Row.Field(START_TIME).Gt(startTime).And(rt.Row.Field(END_TIME).Lt(endTime))
    }

    return nil
}
```

**Comment by AlexLuya** [comment]
but why?And if so,how can I check whether something got returned?RqlTerm hasn't builtin method like:IsValid() to support checking and all fields are private.

**Comment by dancannon** [comment]
Basically the code you gave is not valid Go code. Also I am not really sure why you would want to use a pointer for this. I think it would make more sense to use the following code (I apologise for not properly reading your question before).  I am assuming that you do not want your query to be filtered if the start time is -1 

``` go
 func ForTime(startTime, endTime int64) interface{} {
    if startTime != -1 {
        return rt.Row.Field(START_TIME).Gt(startTime).And(rt.Row.Field(END_TIME).Lt(endTime))
    }

    return true
}
```

The change that I made is to replace the function return type with `interface{}` and change the return value to `true`. I hope this helps.

Regarding the validation of queries I try to use the compiler for all validation however due to the fact that RethinkDB is designed for dynamic languages there is only so much I can do. Any errors will either occur at compile time or when running the `Run` function on a term.

**Comment by AlexLuya** [comment]
Thanks.I really have changed my design as your this suggestion after got your previous answer,but  rather than "return true",I used "return nil".

**Comment by ghost** [comment]
Is that function going to be used inside r.Reduce() or something? If so, `if` clause will not function as you expect it. Return `r.Branch(condition, result, elseResult)` instead.
